better error message

diff --git a/.github/workflows/create_builds.yaml b/.github/workflows/create_builds.yaml
--- a/.github/workflows/create_builds.yaml
+++ b/.github/workflows/create_builds.yaml
@@ -26,7 +26,10 @@ jobs:
           python -m pip install --upgrade pip setuptools wheel
           python setup.py sdist | tee output.txt
           test ${PIPESTATUS[0]} -eq 0
-          test "v$(grep -q 'GITLAB_VERSION' output.txt)" == "${{ github.event.release.tag_name }}"
+          if [ "v$(grep -q 'GITLAB_VERSION' output.txt)" != "${{ github.event.release.tag_name }}" ]; then
+            echo "::error::Version mismatch between setup.py and release tag"
+            exit 1
+          fi
           grep '^GITLAB_' output.txt >> $GITHUB_OUTPUT
 
       - name: Upload Release Assets
